snakeeyes/blueprints/billing/views/billing.py
from flask import (
  Blueprint,
  current_app,
  render_template,
  url_for,
  request,
  redirect,
  flash,
)

from flask_login import login_required, current_user
from flask_babel import gettext as _

from config import settings
from lib.util_json import render_json
from snakeeyes.blueprints.billing.forms import SubscriptionForm, \
    UpdateSubscriptionForm, CancelSubscriptionForm, PaymentForm
from snakeeyes.blueprints.billing.models.coupon import Coupon
from snakeeyes.blueprints.billing.models.subscription import Subscription
from snakeeyes.blueprints.billing.models.invoice import Invoice
from snakeeyes.blueprints.billing.decorators import subscription_required, \
    handle_stripe_exceptions

billing = Blueprint('billing', __name__, template_folder='../templates',
                    url_prefix='/subscription')


@billing.route('/pricing')
def pricing():
    if current_user.is_authenticated and current_user.subscription:
        return redirect(url_for('billing.update'))

    form = UpdateSubscriptionForm()

    return render_template('billing/pricing.html', form=form,
                           plans=settings.STRIPE_PLANS)


@billing.route('/coupon_code', methods=['POST'])
@login_required
def coupon_code():
    code = request.form.get('coupon_code')
    if code is None:
        return render_json(422,
                           {'error': 'Coupon code cannot be processed.'})

    coupon = Coupon.find_by_code(code)
    if coupon is None:
        return render_json(404, {'error': 'Coupon code not found.'})

    return render_json(200, {'data': coupon.to_json()})


@billing.route('/create', methods=['GET', 'POST'])
@handle_stripe_exceptions
@login_required
def create():
    if current_user.subscription:
        flash(_('You already have an active subscription.'), 'info')
        return redirect(url_for('user.settings'))

    plan = request.args.get('plan')
    subscription_plan = Subscription.get_plan_by_id(plan)

    # Guard against an invalid or missing plan.
    if subscription_plan is None and request.method == 'GET':
        flash(_('Sorry, that plan did not exist.'), 'error')
        return redirect(url_for('billing.pricing'))

    stripe_key = current_app.config.get('STRIPE_PUBLISHABLE_KEY')
    form = SubscriptionForm(stripe_key=stripe_key, plan=plan)

    if form.validate_on_submit():
        subscription = Subscription()
        created = subscription.create(user=current_user,
                                      name=request.form.get('name'),
                                      plan=request.form.get('plan'),
                                      coupon=request.form.get('coupon_code'),
                                      token=request.form.get('stripe_token'))

        if created:
            flash(_('Awesome, thanks for subscribing!'), 'success')
        else:
            flash(_('You must enable JavaScript for this request.'), 'warning')

        return redirect(url_for('user.settings'))

    return render_template('billing/payment_method.html',
                           form=form, plan=subscription_plan)


@billing.route('/update', methods=['GET', 'POST'])
@handle_stripe_exceptions
@subscription_required
@login_required
def update():
    current_plan = current_user.subscription.plan
    active_plan = Subscription.get_plan_by_id(current_plan)
    new_plan = Subscription.get_new_plan(request.form.keys())

    plan = Subscription.get_plan_by_id(new_plan)

    # Guard against an invalid, missing or identical plan.
    is_same_plan = new_plan == active_plan['id']
    if ((new_plan is not None and plan is None) or is_same_plan) and \
            request.method == 'POST':
        return redirect(url_for('billing.update'))

    form = UpdateSubscriptionForm(coupon_code=current_user.subscription.coupon)

    if form.validate_on_submit():
        subscription = Subscription()
        updated = subscription.update(user=current_user,
                                      coupon=request.form.get('coupon_code'),
                                      plan=plan.get('id'))

        if updated:
            flash(_('Your subscription has been updated.'), 'success')
            return redirect(url_for('user.settings'))

    return render_template('billing/pricing.html',
                           form=form,
                           plans=settings.STRIPE_PLANS,
                           active_plan=active_plan)


@billing.route('/cancel', methods=['GET', 'POST'])
@handle_stripe_exceptions
@login_required
def cancel():
    if not current_user.subscription:
        flash(_('You do not have an active subscription.'), 'error')
        return redirect(url_for('user.settings'))

    form = CancelSubscriptionForm()

    if form.validate_on_submit():
        subscription = Subscription()
        cancelled = subscription.cancel(user=current_user)

        if cancelled:
            flash(_('Sorry to see you go, your subscription has been '
                    'cancelled.'), 'success')
            return redirect(url_for('user.settings'))

    return render_template('billing/cancel.html', form=form)


@billing.route('/update_payment_method', methods=['GET', 'POST'])
@handle_stripe_exceptions
@login_required
def update_payment_method():
    if not current_user.credit_card:
        flash(_('You do not have a payment method on file.'), 'error')
        return redirect(url_for('user.settings'))

    active_plan = Subscription.get_plan_by_id(
        current_user.subscription.plan)

    card = current_user.credit_card
    stripe_key = current_app.config.get('STRIPE_PUBLISHABLE_KEY')
    form = SubscriptionForm(stripe_key=stripe_key,
                            plan=active_plan,
                            name=current_user.name)

    if form.validate_on_submit():
        subscription = Subscription()
        updated = subscription.update_payment_method(user=current_user,
                                                     credit_card=card,
                                                     name=request.form.get(
                                                         'name'),
                                                     token=request.form.get(
                                                         'stripe_token'))

        if updated:
            flash(_('Your payment method has been updated.'), 'success')
        else:
            flash(_('You must enable JavaScript for this request.'), 'warning')

        return redirect(url_for('user.settings'))

    return render_template('billing/payment_method.html', form=form,
                           plan=active_plan, card_last4=str(card.last4))


@billing.route('/billing_details', defaults={'page': 1})
@billing.route('/billing_details/page/<int:page>')
@handle_stripe_exceptions
@login_required
def billing_details(page):
    paginated_invoices = Invoice.query.filter(
      Invoice.user_id == current_user.id) \
        .order_by(Invoice.created_on.desc()).paginate(page, 12, True)

    if current_user.subscription:
        upcoming = Invoice.upcoming(current_user.payment_id)
        coupon = Coupon.query \
            .filter(Coupon.code == current_user.subscription.coupon).first()
    else:
        upcoming = None
        coupon = None

    return render_template('billing/billing_details.html',
                           paginated_invoices=paginated_invoices,
                           upcoming=upcoming, coupon=coupon)


@billing.route('/purchase_coins', methods=['GET', 'POST'])
@login_required
def purchase_coins():
    stripe_key = current_app.config.get('STRIPE_PUBLISHABLE_KEY')
    form = PaymentForm(stripe_key=stripe_key)

    if form.validate_on_submit():
        coin_bundles = current_app.config.get('COIN_BUNDLES')
        coin_bundles_form = int(request.form.get('coin_bundles'))

        bundle = next((item for item in coin_bundles if
                       item['coins'] == coin_bundles_form), None)

        if bundle is not None:
            invoice = Invoice()
            created = invoice.create(user=current_user,
                                     currency=current_app.config.get(
                                      'STRIPE_CURRENCY'),
                                     amount=bundle.get('price_in_cents'),
                                     coins=coin_bundles_form,
                                     coupon=request.form.get('coupon_code'),
                                     token=request.form.get('stripe_token'))

            if created:
                flash(_('%(amount)s coins have been added to your account.',
                        amount=coin_bundles_form), 'success')
            else:
                flash(_('You must enable JavaScript for this request.'),
                      'warning')

            return redirect(url_for('bet.place_bet'))

    return render_template('billing/purchase_coins.html', form=form)

snakeeyes/blueprints/billing/templates/billing/macros/billing.html
{% import 'macros/form.html' as f with context %}
{% import 'macros/items.html' as items %}

{% macro card_expiring_warning() -%}
  {% if current_user.is_authenticated and 
        current_user.subscription and current_user.credit_card.is_expiring %}
    <div class="alert alert-warning" role="alert">
      <div class="container">
        Your credit card is going to expire soon,
        <a href="{{ url_for('billing.update_payment_method') }}">
          please update it</a>
        .
      </div>
    </div>
  {% endif %}
{%- endmacro %}


{% macro plan(plan) -%}
  <div class="col-md-4{{ ' scale-up' if plan.metadata.recommended }} {{ ' quarter-faded' if not plan.metadata.recommended }}">
    <div class="panel panel-default{{ ' panel-danger' if plan.metadata.recommended }}">
      <div class="panel-heading text-center"><h3>{{ plan.name }}</h3></div>
      <div class="panel-body">
        {{ caller () }}

        {% if current_user.is_authenticated %}
          {% if current_user.subscription %}
            {% if plan == active_plan %}
              <strong class="btn btn-default btn-lg btn-block">
                Current plan
              </strong>
            {% else %}
              <button id="submit_{{ plan.id }}" name="submit_{{ plan.id }}"
                      class="btn btn-primary btn-lg btn-block">
                <img src="{{ url_for('static', filename='images/spinner.gif') }}"
                     class="spinner"
                     width="16" height="11" alt="Spinner"/>
                Change plan
              </button>
            {% endif %}
          {% else %}
            <a href="{{ url_for('billing.create', plan=plan.id) }}"
               class="btn btn-primary btn-lg btn-block">Continue</a>
          {% endif %}
        {% else %}
          <a href="{{ url_for('user.signup') }}"
             class="btn btn-primary btn-lg btn-block">
            Sign up
          </a>
        {% endif %}

        <p class="small text-muted sm-margin-top text-center">
          ${{ plan.amount | format_currency }} / {{ plan.interval }}
        </p>
      </div>
    </div>
  </div>
{%- endmacro %}


{% macro coupon_data(coupon) -%}
  {% if coupon.amount_off %}
    {% set discount = '$' + coupon.amount_off | format_currency %}
  {% else %}
    {% set discount = coupon.percent_off | string + '%' %}
  {% endif %}
  {% if coupon.duration == 'forever' %}
    {% set label = 'It is saving you ' + discount + ' per month forever.' %}
  {% elif coupon.duration == 'once' %}
    {% set label = 'It saved you ' + discount + ' this month.' %}
  {% else %}
    {% set label = 'It is saving you ' + discount + ' for the next ' + coupon.duration_in_months | string + ' months.' %}
  {% endif %}

  {{ label }}
{%- endmacro %}


{% macro coupon_duration_tag_for(coupon) -%}
  {% if coupon.duration == 'forever' %}
    <span class="label label-success">Forever</span>
  {% elif coupon.duration == 'once' %}
    <span class="label label-warning">Once</span>
  {% else %}
    <span class="label label-info">
      {{ coupon.duration_in_months }} months
    </span>
  {% endif %}
{%- endmacro %}


{% macro coupon_expiration(coupon) -%}
  {% if coupon.redeem_by %}
    <time class="from-now"
          data-datetime="{{ coupon.redeem_by }}">
      {{ coupon.redeem_by }}
    </time>
  {% elif coupon.duration_in_months %}
    &mdash;
  {% else %}
    Never
  {% endif %}
{%- endmacro %}


{% macro coupon_redeemed(times_redeemed, max_redemptions) -%}
  {% set total = max_redemptions if max_redemptions else '&infin;' | safe %}
  {{ times_redeemed }} / {{ total }}
{%- endmacro %}


{% macro coupon_discount(amount_off, percent_off) -%}
  {% if amount_off %}
    ${{ amount_off | format_currency }}
  {% else %}
    {{ percent_off }}%
  {% endif %}
{%- endmacro %}


{% macro subscription_details(coupon) -%}
  <h2>Subscription details</h2>
  {% if coupon %}
    <div class="alert alert-info alert-small">
      Coupon code <strong>{{ coupon.code }}</strong> is applied to your
      subscription.
    </div>
    <span class="small text-muted">
      {{ coupon_data(coupon) }}
    </span>
    <br class="sm-margin-bottom">
    <br class="sm-margin-bottom">
  {% endif %}
{%- endmacro %}


{% macro upcoming_invoice(invoice) -%}
  {% if invoice == None %}
    <h3>No upcoming payments</h3>
    <p>You are not currently subscribed, so there's nothing to see here.</p>
  {% else %}
    <table class="table table-striped sm-margin-bottom">
      <thead>
        <tr>
          <th>Subscription</th>
          <th>Description</th>
          <th>Next billing date</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ invoice.plan }}</td>
          <td>{{ invoice.description }}</td>
          <td>
            <time class="short-date" data-datetime="{{ invoice.next_bill_on }}">
              {{ invoice.next_bill_on }}
            </time>
          </td>
          <td>
            ${{ invoice.amount_due | format_currency }}
            <span class="color--muted"> / {{ invoice.interval }}</span>
          </td>
        </tr>
      </tbody>
    </table>
  {% endif %}
{%- endmacro %}


{% macro invoices(invoices) -%}
  <h2>Billing history</h2>
  {% if invoices.total == 0 %}
    <h4>No invoices found</h4>
    <p>This isn't an error. You just haven't been invoiced yet.</p>
  {% else %}
    <table class="table table-striped sm-margin-bottom">
      <thead>
        <tr>
          <th>Date</th>
          <th>Method</th>
          <th>Description</th>
          <th>Service period</th>
          <th>Tax</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      {% for invoice in invoices.items %}
        <tr>
          <td>
            <time class="from-now" data-datetime="{{ invoice.created_on }}">
              {{ invoice.created_on }}
            </time>
          </td>
          <td class="small">
            {{ invoice.brand }} ****{{ invoice.last4 }}
          </td>
          <td class="small">{{ invoice.description }}</td>
          <td>
            <time class="short-date" data-datetime="{{ invoice.period_start_on }}">
              {{ invoice.period_start_on }}
            </time>
            <span class="text-info">&mdash;</span>
            <time class="short-date" data-datetime="{{ invoice.period_end_on }}">
              {{ invoice.period_end_on }}
            </time>
          </td>
          <td title="{{ (invoice.tax_percent | round(2)) | string + '%' if invoice.tax_percent }}">
            {{ '$' + invoice.tax | format_currency if invoice.tax }}
          </td>
          <td title="{{ invoice.currency }}">
            ${{ invoice.total | format_currency }}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {{ items.paginate(invoices) }}
  {% endif %}
{%- endmacro %}


{% macro payment_form(form, button_label, with_coupon) -%}
  {% set button_label = _(button_label) %}

  <div class="alert alert-small alert-danger payment-errors"></div>

  <noscript>
    <p class="alert alert-sm alert-warning text-center sm-margin-top">
      {{ _('You need to enable JavaScript to proceed.') }}
    </p>
  </noscript>

  {% if with_coupon %}
      <div class="coupon-code">
        {{ form.coupon_code.label }}
        {{ f.field(form.coupon_code) }}
          <div id="coupon_code_status"
               class="small alert alert-small alert-success">
          </div>
      </div>
  {% endif %}

  {% call f.form_group(form.name, css_class='sm-margin-bottom',
                       autofocus='autofocus') %}
  {% endcall %}

  <div class="form-group">
    <label for=""><strong>{{ _('Card number') }}</strong></label>
    <input data-stripe="number" class="form-control"
           value="{{ '****' + card_last4 if card_last4 }}"/>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group pull-left form-inline">
        <label for="" class="block">
          <strong>{{ _('Exp. date') }}</strong>
        </label><br/>
        <select data-stripe="exp-month" class="form-control cc-details">
          <option value=""></option>
          {% for month in range(1,13) %}
            <option value="{{ '%02d' % month }}">
              {{ '%02d' % month }}
            </option>
          {% endfor %}
        </select>
        <select data-stripe="exp-year" class="form-control cc-details">
          <option value=""></option>
          {% for year in range(current_year(),current_year()+15) %}
            <option value="{{ '%04d' % year }}">
              {{ '%04d' % year }}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group pull-right">
        <label for="">
          <strong>
            <abbr title="3-4 digit code on the back">CVC</abbr>
          </strong>
        </label>
        <input data-stripe="cvc" class="form-control cc-details"/>
      </div>
    </div>
  </div>

  <button type="submit" class="btn btn-primary btn-block lg-margin-bottom">
    <img src="{{ url_for('static', filename='images/spinner.gif') }}"
         class="spinner"
         width="16" height="11" alt="Spinner"/>
    {{ button_label }}
  </button>

  <div class="text-center quarter-faded">
    <img src="{{ url_for('static', filename='images/cc/visa.png') }}"
          width="40" height="24" class="cc-images" alt="Visa"/>
    <img src="{{ url_for('static', filename='images/cc/mastercard.png') }}"
          width="40" height="24" class="cc-images"
          alt="Mastercard"/>
    <img src="{{ url_for('static', filename='images/cc/american-express.png') }}"
          width="40" height="24" class="cc-images"
          alt="American Express"/>
    <img src="{{ url_for('static', filename='images/cc/jcb.png') }}"
          width="40" height="24" class="cc-images" alt="J.C.B"/>
    <img src="{{ url_for('static', filename='images/cc/diners-club.png') }}"
          width="40" height="24" class="cc-images"
          alt="Diner's Club"/>

    <div class="text-success sm-margin-top">
      <i class="fa fa-fw fa-lock"></i>
      <span class="small">
        {{ _('Protected by 128-bit SSL encryption') }}
      </span>
    </div>
  </div>
{%- endmacro %}